[package]
name = "kitty-api"
version = "0.2.0"
authors = ["kittyandrew <kitty@maudrew.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
rocket_contrib = { version = "0.4.6", features = ["tera_templates"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
