version: "3.7"
services:
  db:
    container_name: kitty-api-db
    image: kitty-api-db
    restart: always
    build: postgres
    environment:
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=hackme
      - POSTGRES_DB=kittybox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitty"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: kitty-api
    image: kitty-api
    restart: always
    build: .
    environment:
      - TOKEN
    depends_on:
      - db

networks:
  default:
    external:
      name: caddynet
