version: "3.7"
services:
  api:
    container_name: kitty-api
    image: kitty-api
    restart: always
    build: .
    environment:
      - TOKEN

networks:
  default:
    external:
      name: caddynet
