[global]
address = "0.0.0.0"
template_dir = "templates/"

[global.databases]
kittybox = { url = "postgres://kitty:hackme@localhost:5432/kittybox" }

# Release config
[release]
# default port is 8000
port = 8080

[release.databases]
kittybox = { url = "postgres://kitty:hackme@kitty-api-db:5432/kittybox" }
