CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  age INTEGER NOT NULL,
  active BOOLEAN NOT NULL,
  picture TEXT NOT NULL
);

CREATE TABLE cats (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  breed TEXT NOT NULL,
  age INTEGER NOT NULL,
  weight INTEGER NOT NULL,
  picture TEXT NOT NULL
);

CREATE TABLE textcats (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  is_ascii BOOLEAN NOT NULL,
  length INTEGER NOT NULL
);
