version: "3.7"
services:
  db:
    container_name: kitty-api-db
    image: kitty-api-db
    restart: always
    build: .
    environment:
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=hackme
      - POSTGRES_DB=kittybox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitty"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Develop config
    ports:
      - 5432:5432
